name: terra-draw Dry-run Release

permissions:
  contents: write

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.TERRA_DRAW_PAT }}

      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: npm ci

      - name: Update Docs
        run: npm run docs

      - name: Run build
        working-directory: ./packages/terra-draw
        run: npm run build

      - name: Set git credentials
        run: |
          git config --global user.email "terradraw@githubactions.com"
          git config --global user.name "James Milner"

      - name: Dry Run Release
        working-directory: ./packages/terra-draw
        run: npm run release:dryrun